theme: jekyll-theme-minimal
title: Roziana Rodrigues
description: Front-End Software Developer
logo: https://avatars.githubusercontent.com/u/19981551?s=400&u=9350bcbf45747c0ab012a83adb748fb4955e0349&v=4
show_downloads: false
